### ISSUE TITLE
SSL Connection error

### ISSUE THREAD

**Issue by dipterix** [coinbase/coinbase-python#25]
Traceback (most recent call last):
  File "C:\Users\mboyle\Desktop\tmp.py", line 5, in <module>
    user = sandbox_client.get_current_user()
  File "C:\Python27\lib\site-packages\coinbase-2.0.6-py2.7.egg\coinbase\wallet\client.py", line 213, in get_current_user
    response = self._get('v2', 'user', data=params)
  File "C:\Python27\lib\site-packages\coinbase-2.0.6-py2.7.egg\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', _args, *_kwargs)
  File "C:\Python27\lib\site-packages\coinbase-2.0.6-py2.7.egg\coinbase\wallet\client.py", line 115, in _request
    response = getattr(self.session, method)(uri, *_kwargs)
  File "C:\Python27\lib\site-packages\requests-2.10.0-py2.7.egg\requests\sessions.py", line 487, in get
    return self.request('GET', url, *_kwargs)
  File "C:\Python27\lib\site-packages\requests-2.10.0-py2.7.egg\requests\sessions.py", line 475, in request
    resp = self.send(prep, *_send_kwargs)
  File "C:\Python27\lib\site-packages\requests-2.10.0-py2.7.egg\requests\sessions.py", line 585, in send
    r = adapter.send(request, *_kwargs)
  File "C:\Python27\lib\site-packages\requests-2.10.0-py2.7.egg\requests\adapters.py", line 477, in send
    raise SSLError(e, request=request)
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

**Comment by anthonywittemann** [comment]
I have the same error when trying to use the client.
Using python 2.7.11 on Mac 10.11.5
I saw a similar issue [here](https://github.com/docker/compose/issues/890). Perhaps the problem is with homebrew??

**Comment by aianus** [comment]
Are you able to establish a verified SSL connection to a different host using the Python requests library? Say, `https://www.coinbase.com/` or `https://www.google.com/` ?

**Comment by anthonywittemann** [comment]
@aianus Yes, using the [python requests library](http://docs.python-requests.org/en/master/) I was able to get an HTTP 200 response to my request. Python terminal pasted below:
`import requests`
`r = requests.get('https://api.github.com/user', auth=('anthonywittemann', 'my_password'))`
`r.status_code`
`200`

**Comment by sds** [comment]
I'm going to close since this is an old issue, but if you are still able to reproduce please open a new one and we'll look into it! Thanks.
