### ISSUE TITLE
InternalServerError when calling get_notifications

### ISSUE THREAD

**Issue by qprotex** [coinbase/coinbase-python#70]
When using client.get_notifications() I get the following error:

```
Traceback (most recent call last):
  File "D:/SourceCode/Python/untitled/test.py", line 10, in <module>
    print client.get_notifications()
  File "C:\Python27_32\envs\test\lib\site-packages\coinbase\wallet\client.py", line 268, in get_notifications
    response = self._get('v2', 'notifications', params=params)
  File "C:\Python27_32\envs\test\lib\site-packages\coinbase\wallet\client.py", line 128, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Python27_32\envs\test\lib\site-packages\coinbase\wallet\client.py", line 115, in _request
    return self._handle_response(response)
  File "C:\Python27_32\envs\test\lib\site-packages\coinbase\wallet\client.py", line 124, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.InternalServerError: APIError(id=internal_server_error): An error has occurred. If this problem persists, please visit https://support.coinbase.com for assistance.
```

client.get_notification is working fine.

**Comment by sds** [comment]
Hey @qprotex, thanks for the report.

As this is an issue with the API and not the Python library itself, as the error message suggests you should reach out to our [support team](https://support.coinbase.com/customer/en/portal/articles/2288496-how-can-i-contact-coinbase-support-) for assistance. Thanks!
