### ISSUE TITLE
Invalid signature

### ISSUE THREAD

**Issue by Mehodin** [coinbase/coinbase-python#88]
```import json, hmac, hashlib, time, requests
from coinbase.wallet.client import Client
import time

API_KEY = ''
API_SECRET = ''

client = Client(API_KEY, API_SECRET)
print(client.get_primary_account())


Traceback (most recent call last):
  File "test.py", line 10, in <module>
    print(client.get_primary_account())
  File "C:\Users\Mehodin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\coinbase\wallet\client.py", line 247, in get_primary_account
    return self.get_account('primary', **params)
  File "C:\Users\Mehodin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\coinbase\wallet\client.py", line 242, in get_account
    response = self._get('v2', 'accounts', account_id, params=params)
  File "C:\Users\Mehodin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\coinbase\wallet\client.py", line 129, in _get
    return self._request('get', *args, **kwargs)
  File "C:\Users\Mehodin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\coinbase\wallet\client.py", line 116, in _request
    return self._handle_response(response)
  File "C:\Users\Mehodin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\coinbase\wallet\client.py", line 125, in _handle_response
    raise build_api_error(response)
coinbase.wallet.error.AuthenticationError: APIError(id=authentication_error): invalid signature
```

How do i resolve this?

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
